config/routes.rb
Rails.application.routes.draw do
  get 'calorie_calculator/index'

  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'Calorie Calculator', to: 'calorie_calculator#index', as: 'calorie_calculator'

  resources :users
  resources :calorie_calculator
  get 'page/index'


  root 'page#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    email_format: { message: "is invalid." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
  
end

app/controllers/calorie_calculator_controller.rb
class CalorieCalculatorController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calorie_calculator_helper.rb
module CalorieCalculatorHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calorie_calculator/index.html.erb
<h1>CalorieCalculator#index</h1>
<p>Find me in app/views/calorie_calculator/index.html.erb</p>

<h1>Age</h1>
<input type="number" id="age" placeholder="Your age"><br>

<h2>Gender</h2>
<input type="radio" name="gender" value="male" checked> Male<br>
<input type="radio" name="gender" value="female"> Female<br>

<h3>Height</h3>
<input type = "number" id="feet" placeholder="Feet"> Feet
<input type = "number" id="inches" placeholder="Inches"> Inches <br> 
or<br>
<input type = "number" id="cm" placeholder="Centimeters"> Centimeters

<h4>Weight</h4>
<input type = "number" id="pound" placeholder="pounds"> Pounds <br>
or<br>
<input type = "number" id="kg" placeholder="KG"> KG

<h5>Activity Level</h5>
<input type="checkbox" name="exercise_level" value="Little to no exercise" checked> Little to no exercise :( <br>
<input type="checkbox" name="exercise_level" value="3 times a week" > 3 times a week <br>
<input type="checkbox" name="exercise_level" value="4 times a week" > 4 times a week <br>
<input type="checkbox" name="exercise_level" value="5 times a week" > 5 times a week<br>
<input type="checkbox" name="exercise_level" value="Daily" > Daily <br>

<input type="submit" value="Calculate!"> <br>

<%= link_to 'Back', users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMPT276Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div id="user_header">
    <% if current_user %>
      Logged in as <%= current_user.email %>
      <%= link_to "Log Out", logout_path%>
    <% else %>
      <%= link_to "Signup", signup_path %> or
      <%= link_to "Log In", login_path %>
      
    <% end %>
    <%= link_to "Calorie Calculator", calorie_calculator_path %>
  </div>
  
  <% flash.each do |key, value| %>
    <%= content_tag(:div, class: "alert alert-#{key}") do %>
      <p><%= value %></p>
    <% end %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/schedule/schedule.html.erb
<div class="container">
  <h2>Schedule For Test</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>User Name</th>
        <th>Date</th>
        <th>Running</th>
        <th>Workout</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>test</td>
        <td>16/06/19</td>
        <td>Yes</td>
        <td>Yes</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>